version: '3.9'

services:
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/development/php-fpm/build/Dockerfile
        volumes:
            - ./application:/var/www/application
            - var:/var/www/application/var
        depends_on:
            - mysql

    nginx:
        build:
            context: .
            dockerfile: ./docker/development/nginx/build/Dockerfile
        volumes:
            - ./application/api/public:/var/www/application/api/public:ro
            - ./docker/development/nginx/etc/conf.d:/etc/nginx/conf.d:ro
        ports:
            - "8000:80"
        depends_on:
            - php-fpm

    mysql:
        image: mysql:8
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        # restart: always # always restart unless stopped manually
volumes:
    database: ~
    var: ~
